### ISSUE TITLE
trouble installing class-dump-z

### ISSUE THREAD

**Issue by TaichiAkimoto** [ivRodriguezCA/RE-iOS-Apps#4]
Hi, 

I am having trouble installing class-dump-z on my mac high-sierra.
I have followed the link on README and downloaded files.

I have cp class-dump-z under /usr/local/bin, then restart my terminal.
But, when I type
```
sudo class-dump-z [file-name]
```
class-dump-z not found error occurs.
Please tell me if I am doing something wrong. 

Thank you for nice tutorial.

**Comment by ivRodriguezCA** [comment]
Hey @TaichiAkimoto,

Thanks for reading!

Have you tried giving it `executable` permissions?

```bash
chmod +x /usr/local/bin/class-dump-z
```

**Comment by TaichiAkimoto** [comment]
It worked.
Thank you very much!!
