### ISSUE TITLE
unc0ver jailbreak - bfinject

### ISSUE THREAD

**Issue by TheM4hd1** [ivRodriguezCA/RE-iOS-Apps#6]
Hello,
as you mentioned `bfinject` only works on 2 specific jailbreaks.
How about `unc0ver` jailbreak on iOS 12.1.4 ? there is no update for it.
I saw something on Cydia named `CrackerXI` but it seems it only supports until `12.1.2`
So I'll appreciate any help.
thanks.

**Comment by TheM4hd1** [comment]
Update: I was able to use `CrackerXI` on `iOS 12.1.4` to decrypt and download `.ipa`.
I'll update this issue if everything works as expected.

**Comment by ivRodriguezCA** [comment]
Thanks for sharing, I updated the writeup to use [frida-ios-dump](https://github.com/AloneMonkey/frida-ios-dump) on iOS 12.x jailbreaks.
