### ISSUE TITLE
Add versioning and maybe .epub version

### ISSUE THREAD

**Issue by natalia-osa** [ivRodriguezCA/RE-iOS-Apps#7]
In fact 2 improvements in 1 issue:

1) Add versioning to the book. This way, it'll be easier after some time to come back and see that something important has changed, or the version is still the same, so nothing changed.

2) A possibility to download a handy epub would be useful for e-reader users. Most of these currently does support links, and it's useful as a quick reference.

Because many people probably have no idea how to do it, here's an example which I did:
- download everything from the repo
- use pandoc (http://pandoc.org/) `pandoc -o README.epub README.md` for all of the .md files here
- use calibre with EpubMerge plugin to merge the files from the previous point
- fill all of the data to give a credit for the repo owner, eventually create a custom cover :-)

I'm attaching the epub I've created with todays timestamp, so it is 30.09.2019, maybe it'll be useful for someone. Btw if there would be versioning, I wouldn't have to handle with the timestamp but with the version number instead. There are only 3 files inside: epub, jpg, opf.
[ebook (epub) from the repo - 30.09.2019](https://github.com/ivRodriguezCA/RE-iOS-Apps/files/3671807/Reverse.Engineering.iOS.Applications.zip)

**Comment by ivRodriguezCA** [comment]
Thank you Natalia for your suggestions. Both of these are fantastic ideas!

I updated the main README.md with the version and a link to the `.epub` file.

Thanks again this was absolutely brilliant!
